### PR TITLE
Version 3.0.0

### LINKED ISSUE #64: Add debug tools
e.x. get sources, get source last scraped time, etc

### LINKED ISSUE #65: Dynamic parser: Make axios build-in and support ignoreCertificates

### LINKED ISSUE #66: Allow more than one category per url

### PR DESCRIPTION
**Pull request by JexSrs**
* Removed article hash field, it will be replaced by `${this.link}:${this.title}`. To change than just override getHash function.
* Removed database, instead the user have to implement the functions. This allows the user to use whatever database they want without affecting Saffron.
* Allow multiple categories per URL.
* Added some debug tools.
* Allow Saffron's scheduler to continue from where it left of.
* Finally implemented grid using socket.io. No built-in encryption the user may add key, cert files for HTTPS support.
* Class serialization was added for Article, Source, Job, Instructions and TextDecoder.
* Dynamic parser's scrape function will take utils and Article as parameter without Saffron changing the function itself.
* Merged utils for all parsers.
* Parsers are using utils.get instead of directly using axios. This helps to not implement ignoreCertificates for each parser.
* Updated package.json right before esm packages.
* Organized files and exported types.

### CODE REVIEW

**Comment by JexSrs** [comment]
For everyone bored to read the commits, v3 is a cleanup of the code and new features that are "explained" at the associated issues. Also the feature of keeping sessions for the scheduler was added.

**Comment by JexSrs** [comment]
We will not merge this pull request until grid is completed

**Comment by JexSrs** [comment]
Grid is completed, but tests are required.

**Review by donfn — APPROVED** [review]
Very nice! Great job mate!

**Pull request merged**
